### ISSUE TITLE
RLHF Tracker

### ISSUE THREAD

**Issue by SalmanMohammadi** [pytorch/torchtune#2081]
```[tasklist]
### Tasks
- [ ] Full-finetune DPO single device recipe
- [ ] Full-finetune distributed DPO recipe
- [ ] #1262
- [ ] PPO tutorial/deep dive
- [ ] DPO tutorial/deep dive
- [ ] Multimodal support for DPO
- [ ] Sample packing for preference datasets
- [ ] General support for classification models for PPO
- [ ] Reward modelling recipe
```
